app_paths:
    processed_log_files: "PROCESSED_FILES"
    error_log_files: "ERROR_FILES"
watcher:
    directory: "LogRsync"
scheduler:
    time_interval: 300
logging:
    level: DEBUG
queue:
    processing_queue: yes
    time: 0.2      
other:
    max_retries: 10
    timeout: 60 
    endpoint_to_check : "https://herculesppd.lefebvre.es/"       
    # https://online.elderecho.com/ for production