app_paths:
    processed_log_files: "PROCESSED_FILES"    
watcher:
    directory: "LogRsync"
scheduler:
    time_interval: 50
logging:
    filename: "monitor.log"
    level: DEBUG
    archive: "archive_logging"
error:
    filename: "error.log"
    archive: "archive_error"
queue:
    processing_queue: yes
    time: 0.1      
other:
    max_retries: 10
    timeout: 60 
    endpoint_to_check : "https://herculesppd.lefebvre.es/"       
    # https://online.elderecho.com/ for production