app_paths:
    processed_files: "Processed_files"
    error_files: "Error_files"
watcher:
    directory: "LogRsync"
scheduler:
    time_interval: 30
logging:
    level: DEBUG
queue:
    processing_queue: yes
    time: 0.2      
other:
    max_retries: 10
            
    